version: 0.2
phases:
  pre_build:
    commands:
      - docker login --username nardoarevalo@me.com -p $DOCKERPASSWORD
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z3r6l3x6
  build:
    commands:
      - docker build -t fairpricepokeapi .
      - docker tag fairpricepokeapi:latest public.ecr.aws/z3r6l3x6/fairpricepokeapi:latest
  post_build:
    commands:
      - docker push public.ecr.aws/z3r6l3x6/fairpricepokeapi:latest
