version: 0.2
phases:
  pre_build:
    commands:
      - |
        if [ $ENVIRONMENT=="integration" ]; then
          if [ $BUILD_KIND=="eks" ]; then
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z3r6l3x6
          fi
        fi

  build:
    commands:
      - |
        if [ $ENVIRONMENT=="integration" ]; then
          if [ $BUILD_KIND=="eks" ]; then
            docker build -t fairpricepokeapi .
            docker tag fairpricepokeapi:latest public.ecr.aws/z3r6l3x6/fairpricepokeapi:latest
          else
            sam build
          fi
        fi
          

  post_build:
    commands:
      - |
        if [ $ENVIRONMENT=="integration" ]; then
          if [ $BUILD_KIND=="eks" ]; then
            echo "Pushing image"
            docker push public.ecr.aws/z3r6l3x6/fairpricepokeapi:latest
          else
            sam deploy
          fi
        fi
       
