AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pokemon-mapper

  Sample SAM Template for pokemon-mapper

Parameters:
  PokemonTgcApiKeyParam:
    Type: AWS::SSM::Parameter::Value<SecureString>
    Default: 'PokemonTgcApiKey'
    Description: Api key to use against pokemon api


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 128
    Environment:
      Variables:
        PokemonTgcApiKey: !Ref PokemonTgcApiKeyParam

Resources:
  PokemonMapperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        PokemonMapperApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PokemonMapperApi:
    Description: "API Gateway endpoint URL for Prod stage for Pokemon Mapper function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PokemonMapperFunction:
    Description: "Pokemon Mapper Lambda Function ARN"
    Value: !GetAtt PokemonMapperFunction.Arn
