# Example cicd codepipeline to run via cloudformation cli to create a
# pipeline that pulls down the source, builds the code, and deploys via AWS CodePipeline
# Command to run is:
#  aws cloudformation create-stack \
#  --stack-name PokeApiBuildImageFromCfStack \
#  --template-body file://codebuild.yml \
#  --region us-east-1

Resources:
  PokeApiBuildImageFromCf:
    Type: AWS::CodeBuild::Project
    Properties:
      Source:
        Type: GITHUB
        Location: 'https://github.com/nardoguy14/AwsServerlessExample.git'
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        ReportBuildStatus: false
        InsecureSsl: false
      SecondarySources: [ ]
      SourceVersion: integration
      SecondarySourceVersions: [ ]
      Artifacts:
        Type: NO_ARTIFACTS
      SecondaryArtifacts: [ ]
      Cache:
        Type: NO_CACHE
      Environment:
        Type: LINUX_CONTAINER
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:4.0'
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Value: integration
            Type: PLAINTEXT
          - Name: DOCKERPASSWORD
            Value: CAMera14
            Type: PLAINTEXT
        PrivilegedMode: true
        ImagePullCredentialsType: CODEBUILD
      ServiceRole: >-
        arn:aws:iam::132856321237:role/service-role/codebuild-PokeApiBuildImage-service-role
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: 'arn:aws:kms:us-east-1:132856321237:alias/aws/s3'
      Tags: [ ]
      BadgeEnabled: false
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED
          EncryptionDisabled: false
      FileSystemLocations: [ ]
